### ISSUE TITLE
TypeError: obfuscator is not a function

### ISSUE THREAD

**Issue by doroved** [getkey/rollup-plugin-obfuscator#12]
**Describe the bug**

- [? ] to the best of my knowledge, this is a bug in `rollup-plugin-obfuscator` and not in `javascript-obfuscator`

Hi, I have this error
TypeError: obfuscator is not a function

I'm using code like this.
```JS
import { fileURLToPath, URL } from 'node:url'
import obfuscator from 'rollup-plugin-obfuscator'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  base: '',
  plugins: [vue()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  build: {
    outDir: 'chrome/store/app',
     rollupOptions: {
       output: {
         plugins: [obfuscator({})],
       },
     },
  },
})
```

**Stack trace**
![image](https://user-images.githubusercontent.com/30116541/198884705-859ad6fb-0d0b-4963-906e-53eb710b0d47.png)

**Package versions:**
- `rollup-plugin-obfuscator`: v0.2.2
- `javascript-obfuscator`: v4.0.0
- `vite`: v3.0.1

**Comment by molinla** [comment]
this working in viteL 3.2.0
![image](https://user-images.githubusercontent.com/61045398/203735818-e1a03548-970d-416f-af05-99417d092cc9.png)

**Comment by doroved** [comment]
> 

How can I use this without TS?

**Comment by doroved** [comment]
> this working in vite: 3.2.0 ![image](https://user-images.githubusercontent.com/61045398/203735818-e1a03548-970d-416f-af05-99417d092cc9.png)
> 
> ```
> import obfuscatorModule, { RollupPluginObfuscatorOptions } from "rollup-plugin-obfuscator";
> 
> const obfuscator: (override: Partial<RollupPluginObfuscatorOptions>) => Plugin = (obfuscatorModule as any).default
> ```

How can I use this without TS?

**Comment by molinla** [comment]
> > this working in vite: 3.2.0 ![image](https://user-images.githubusercontent.com/61045398/203735818-e1a03548-970d-416f-af05-99417d092cc9.png)
> > ```
> > import obfuscatorModule, { RollupPluginObfuscatorOptions } from "rollup-plugin-obfuscator";
> > 
> > const obfuscator: (override: Partial<RollupPluginObfuscatorOptions>) => Plugin = (obfuscatorModule as any).default
> > ```
> 
> How can I use this without TS?

just simply remove the type :)
```
import obfuscatorModule from "rollup-plugin-obfuscator";

const obfuscator = obfuscatorModule.default
```

**Comment by doroved** [comment]
> > > this working in vite: 3.2.0 ![image](https://user-images.githubusercontent.com/61045398/203735818-e1a03548-970d-416f-af05-99417d092cc9.png)
> > > ```
> > > import obfuscatorModule, { RollupPluginObfuscatorOptions } from "rollup-plugin-obfuscator";
> > > 
> > > const obfuscator: (override: Partial<RollupPluginObfuscatorOptions>) => Plugin = (obfuscatorModule as any).default
> > > ```
> > 
> > 
> > How can I use this without TS?
> 
> just simply remove the type :)
> 
> ```
> import obfuscatorModule from "rollup-plugin-obfuscator";
> 
> const obfuscator = obfuscatorModule.default
> ```

Yes, that's exactly what I did.)
But I got this message, without obfuscating the code

**_The "transform" hook used by the output plugin rollup-plugin-obfuscator is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin._**
<img width="878" alt="image" src="https://user-images.githubusercontent.com/30116541/203772009-0fbdb8f9-b15f-49e8-9889-51a9f5a141eb.png">

**Comment by molinla** [comment]
> 

 i try to set the obfuscator-config options in both  **"fileOptions"** and **"globalOptions"**, and use cdn to exclude "vue" ,"vue-router" or other libs, it's working.
![image](https://user-images.githubusercontent.com/61045398/203893828-8bab3afc-ab41-46cc-8940-ea6570f19995.png)

this is my config: 
![image](https://user-images.githubusercontent.com/61045398/203893905-abdb0219-b8e9-46b9-b908-2c7c581fdd39.png)

**Comment by molinla** [comment]
### put it in here , everthing will just be fine 👌
![image](https://user-images.githubusercontent.com/61045398/203901213-282bba9e-b18b-478e-9767-04079728db8e.png)

**Comment by getkey** [comment]
Fixed in v1.0.1!

Make sure to read the [usage](https://github.com/getkey/rollup-plugin-obfuscator#usage) again after you update, the API has changed since v1.0.0.
